# Generated by Django 4.2.3 on 2023-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2', '0002_documento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
