# Generated by Django 4.2.3 on 2023-09-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2', '0003_alter_documento_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Necessita Alteracao', 'Necessita Alteracao')], max_length=100),
        ),
    ]
