# Generated by Django 4.2.3 on 2023-10-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2', '0004_alter_documento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='extensao',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
