# Generated by Django 4.2.3 on 2023-10-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2', '0005_documento_extensao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='obs',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
